// Mock task data - Replace with API calls later
import type { Task } from "@/lib/types"

export const mockTasks: Task[] = [
  {
    taskId: "T001",
    taskName: "Phân tích yêu cầu dự án",
    description: "Phân tích và tài liệu hóa các yêu cầu chức năng và phi chức năng của dự án",
    groupId: "G001",
    groupName: "Team Alpha",
    courseId: "C001",
    courseCode: "EXE102",
    checkpointId: "CP001",
    checkpointNumber: 1,
    status: "graded",
    priority: "high",
    dueDate: "2025-02-01",
    createdDate: "2025-01-20",
    submittedDate: "2025-01-30",
    submittedBy: "G001",
    grade: 85,
    maxScore: 100,
    feedback: "Phân tích tốt, cần bổ sung thêm phần non-functional requirements",
    gradedBy: "L001",
    gradedDate: "2025-02-02",
  },
  {
    taskId: "T002",
    taskName: "Thiết kế database schema",
    description: "Thiết kế và tạo database schema với các bảng và quan hệ",
    groupId: "G001",
    groupName: "Team Alpha",
    courseId: "C001",
    courseCode: "EXE102",
    checkpointId: "CP001",
    checkpointNumber: 1,
    status: "submitted",
    priority: "high",
    dueDate: "2025-02-05",
    createdDate: "2025-01-22",
    submittedDate: "2025-02-04",
    submittedBy: "G001",
    maxScore: 100,
  },
  {
    taskId: "T003",
    taskName: "Thiết kế UI/UX mockup",
    description: "Tạo mockup và wireframe cho giao diện người dùng",
    groupId: "G002",
    groupName: "Team Beta",
    courseId: "C001",
    courseCode: "EXE102",
    checkpointId: "CP001",
    checkpointNumber: 1,
    status: "in-progress",
    priority: "medium",
    dueDate: "2025-02-10",
    createdDate: "2025-01-25",
    maxScore: 100,
  },
  {
    taskId: "T004",
    taskName: "Setup môi trường phát triển",
    description: "Cấu hình môi trường phát triển và CI/CD pipeline",
    groupId: "G001",
    groupName: "Team Alpha",
    courseId: "C001",
    courseCode: "EXE102",
    checkpointId: "CP001",
    checkpointNumber: 1,
    status: "graded",
    priority: "medium",
    dueDate: "2025-02-15",
    createdDate: "2025-01-28",
    submittedDate: "2025-02-14",
    submittedBy: "G001",
    grade: 90,
    maxScore: 100,
    feedback: "Setup tốt, pipeline hoạt động ổn định",
    gradedBy: "L001",
    gradedDate: "2025-02-16",
  },
  {
    taskId: "T005",
    taskName: "Phát triển API Backend",
    description: "Xây dựng các API endpoints cho hệ thống",
    groupId: "G001",
    groupName: "Team Alpha",
    courseId: "C001",
    courseCode: "EXE102",
    checkpointId: "CP002",
    checkpointNumber: 2,
    status: "pending",
    priority: "high",
    dueDate: "2025-03-10",
    createdDate: "2025-02-20",
    maxScore: 100,
  },
]

// API placeholder functions
export async function getTasks(): Promise<Task[]> {
  // TODO: Replace with actual API call
  return Promise.resolve(mockTasks)
}

export async function getTasksByGroup(groupId: string): Promise<Task[]> {
  // TODO: Replace with actual API call
  return Promise.resolve(mockTasks.filter((t) => t.groupId === groupId))
}
