// lib/types.ts
// Centralized type definitions for ECGMS
// This file contains all TypeScript interfaces and types used throughout the application

// ===== USER & AUTHENTICATION TYPES =====
export interface User {
  userId: string;
  username: string;
  fullName: string;
  email: string;
  role: "lecturer" | "student" | "admin";
  major?: "SS" | "SE";
  skillSet?: string[];
  birthday?: string;
  contactInfo?: string;
  groupId?: string | null; // <-- THÊM DÒNG NÀY: null hoặc undefined nghĩa là chưa có nhóm
}

// ===== STUDENT WITHOUT GROUP TYPES =====
export interface MajorInfo {
  majorId: string;
  majorCode: string;
  name: string;
  description: string;
}

export interface UserProfileViewModel {
  userId: string;
  fullName: string;
  bio: string;
  avatarUrl: string;
  major: MajorInfo;
  status: string | null;
}

export interface StudentWithoutGroup {
  studentId: string;
  user: {
    id: string;
    username: string;
    email: string;
    skillSet: string;
  };
  userProfileViewModel: UserProfileViewModel;
  majorCode: string;
  coreSkill: string;
}

// ===== COURSE TYPES =====
export interface Course {
  courseId: string;
  courseCode: string;
  courseName: string;
  semester: string;
  year: number;
  lecturerId: string;
  description?: string;
}

// ===== GROUP TYPES =====
export interface Group {
  groupId: string;
  groupName: string;
  courseId: string;
  courseCode: string;
  memberCount: number;
  maxMembers: number; // Thêm số lượng thành viên tối đa
  leaderName: string;
  leaderId: string;
  status: "open" | "lock" | "finalize" | "private"; // Cập nhật trạng thái
  majors: ("SE" | "SS")[];
  createdDate: string;
  members: GroupMember[]; // Thêm danh sách thành viên
  needs: GroupNeeds[]; // Thêm nhu cầu tuyển dụng
  isLockedByRule?: boolean; // Thêm cờ cho business rule "lock nhóm khi có 3 TV"
  approvalStatus: "pending" | "approved" | "rejected"; // Trạng thái phê duyệt
  rejectionReason?: string; // Lý do từ chối
  approvalDate?: string; // Ngày phê duyệt
  approvedBy?: string; // Người phê duyệt
  autoGenerated?: boolean; // Nhóm được tạo tự động bởi hệ thống
  ready?: boolean; // Nhóm đã sẵn sàng nộp hồ sơ/được duyệt
}

export interface GroupMember {
  userId: string;
  fullName: string;
  avatarUrl?: string; // Thêm avatar để hiển thị
}

export interface GroupNeeds {
  major: "SE" | "SS";
  count: number;
}

// ===== GROUP APPROVAL TYPES =====
export interface GroupApprovalAction {
  groupId: string;
  action: "approve" | "reject";
  reason?: string; // Lý do từ chối hoặc ghi chú
  approvedBy: string;
  approvalDate: string;
}

export interface GroupDetail extends Group {
  skills: string[]; // Kỹ năng của nhóm
  groupRoles: GroupRole[]; // Vai trò trong nhóm
}

export interface GroupRole {
  userId: string;
  role: "leader" | "member" | "secretary" | "treasurer";
  assignedDate: string;
}

// ===== LECTURER ACTION TYPES =====
export interface MemberChangeAction {
  groupId: string;
  studentId: string;
  reason: string;
  changedBy: string; // lecturerId
  changedAt: string;
}

export interface ProposeAdjustmentPayload {
  groupId: string;
  proposal: string; // đề xuất điều chỉnh (tách/ghép nhóm, đổi thành viên...)
  proposedBy: string; // lecturerId
  proposedAt: string;
}

export interface TaskAssignmentForm {
  groupId: string;
  taskName: string;
  description?: string;
  assigneeUserId: string;
  dueDate: string;
}

export interface ContributionScoreInput {
  groupId: string;
  studentId: string;
  score: number; // 0-100
}

// ===== GRADE TYPES =====
export interface GradeItem {
  gradeItemId: string;
  courseId: string;
  courseCode: string;
  itemName: string;
  maxScore: number;
  weight: number; // percentage
  type: "group" | "individual";
  description?: string;
}

export interface Grade {
  gradeId: string;
  gradeItemId: string;
  studentId?: string;
  groupId?: string;
  score: number;
  feedback?: string;
  gradedBy: string;
  gradedDate: string;
}

// ===== CHECKPOINT TYPES =====
export interface Checkpoint {
  checkpointId: string;
  courseId: string;
  courseCode: string;
  checkpointNumber: number; // 1, 2, 3, 4
  checkpointName: string;
  startDate: string;
  endDate: string;
  weight: number; // 25% for each checkpoint
  description?: string;
}

// ===== TASK TYPES =====
export interface Task {
  taskId: string;
  taskName: string;
  description: string;
  groupId: string;
  groupName: string;
  courseId: string;
  courseCode: string;
  checkpointId: string;
  checkpointNumber: number;
  assignedTo?: string; // Optional - students self-assign
  assignedToId?: string; // Optional - students self-assign
  status: "pending" | "in-progress" | "submitted" | "graded";
  priority: "low" | "medium" | "high";
  dueDate: string;
  createdDate: string;
  submittedDate?: string;
  submittedBy?: string; // Group submission
  grade?: number; // Task grade (shared by all group members)
  maxScore?: number; // Maximum score for this task
  feedback?: string; // Lecturer feedback
  gradedBy?: string;
  gradedDate?: string;
}

// ===== UTILITY TYPES =====
export type UserRole = "lecturer" | "student" | "admin";
export type Major = "SS" | "SE";
export type GroupStatus = "active" | "inactive";
export type GroupRoleName = "leader" | "member" | "secretary";
export type TaskStatus = "pending" | "in-progress" | "completed";
export type TaskPriority = "low" | "medium" | "high";
export type GradeType = "group" | "individual";

// ===== API RESPONSE TYPES =====
export interface ApiResponse<T> {
  data: T;
  message: string;
  success: boolean;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// ===== FORM TYPES =====
export interface LoginForm {
  username: string;
  password: string;
}

export interface CreateGroupForm {
  groupName: string;
  courseId: string;
  description?: string;
}

export interface CreateTaskForm {
  taskName: string;
  description: string;
  courseId: string;
  checkpointId: string;
  groupIds: string[]; // Multiple groups can be assigned
  priority: TaskPriority;
  dueDate: string;
  maxScore: number;
}

export interface GradeForm {
  score: number;
  feedback?: string;
}

export interface TaskGradeForm {
  taskId: string;
  score: number;
  feedback?: string;
}

// ===== CHECKPOINT GRADE TYPES =====
export interface CheckpointGrade {
  checkpointId: string;
  checkpointNumber: number;
  checkpointName: string;
  groupId: string;
  groupName: string;
  taskGrades: number[]; // Array of task grades
  averageGrade: number; // Average of all task grades
  weight: number; // 25%
  weightedScore: number; // averageGrade * weight / 100
}

export interface CourseFinalGrade {
  courseId: string;
  courseCode: string;
  courseName: string;
  groupId: string;
  groupName: string;
  checkpointGrades: CheckpointGrade[];
  finalGrade: number; // Sum of all checkpoint weighted scores
}

// ===== DASHBOARD TYPES =====
export interface DashboardStats {
  totalStudents: number;
  totalGroups: number;
  totalCourses: number;
  activeTasks: number;
  completedTasks: number;
  pendingTasks: number;
}

export interface RecentActivity {
  id: string;
  type: "task_completed" | "group_created" | "grade_assigned" | "member_added";
  description: string;
  timestamp: string;
  userId: string;
  userName: string;
}

// ===== NOTIFICATION TYPES =====
export interface Notification {
  id: string;
  title: string;
  message: string;
  type: "info" | "success" | "warning" | "error";
  read: boolean;
  createdAt: string;
  userId: string;
}

// ===== SEARCH & FILTER TYPES =====
export interface SearchFilters {
  searchTerm?: string;
  status?: string;
  role?: UserRole;
  major?: Major;
  courseId?: string;
  groupId?: string;
  dateFrom?: string;
  dateTo?: string;
}

export interface SortOptions {
  field: string;
  direction: "asc" | "desc";
}

// ===== EXPORT TYPES FOR EXCEL =====
export interface ExcelExportData {
  students: User[];
  groups: Group[];
  courses: Course[];
  grades: Grade[];
  tasks: Task[];
}

// ===== ERROR TYPES =====
export interface AppError {
  code: string;
  message: string;
  details?: any;
}

export interface ValidationError {
  field: string;
  message: string;
  value?: any;
}
